# LAB | Feature Engineering

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [111]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [113]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

**Check the shape of your data**

In [116]:
df.shape

(8693, 14)

**Check for data types**

In [119]:
df.dtypes

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

**Check for missing values**

In [122]:
df.isna().any()

PassengerId     False
HomePlanet       True
CryoSleep        True
Cabin            True
Destination      True
Age              True
VIP              True
RoomService      True
FoodCourt        True
ShoppingMall     True
Spa              True
VRDeck           True
Name             True
Transported     False
dtype: bool

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value. 

In [125]:
columns = df.columns
df[columns].isna().sum()
df.dropna(subset=columns, inplace=True)
df.reset_index(drop=True, inplace=True)
df.shape
df

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
6601     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
6602     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
6603     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
6604     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
6605     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines   
...           ...        ...           ...     ...     ...                ...   
6601          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
6602          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
6603          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
6604          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
6605        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
6601        False  
6602        False  
6603         True  
6604        False  
6605         True  

[6606 rows x 14 columns]

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [128]:
df['Cabin'] = df['Cabin'].str[0]

- Drop PassengerId and Name

In [131]:
df.drop(columns=['PassengerId', 'Name'], inplace=True)
df

HomePlanet CryoSleep Cabin    Destination   Age    VIP  RoomService  \
0        Europa     False     B    TRAPPIST-1e  39.0  False          0.0   
1         Earth     False     F    TRAPPIST-1e  24.0  False        109.0   
2        Europa     False     A    TRAPPIST-1e  58.0   True         43.0   
3        Europa     False     A    TRAPPIST-1e  33.0  False          0.0   
4         Earth     False     F    TRAPPIST-1e  16.0  False        303.0   
...         ...       ...   ...            ...   ...    ...          ...   
6601     Europa     False     A    55 Cancri e  41.0   True          0.0   
6602      Earth      True     G  PSO J318.5-22  18.0  False          0.0   
6603      Earth     False     G    TRAPPIST-1e  26.0  False          0.0   
6604     Europa     False     E    55 Cancri e  32.0  False          0.0   
6605     Europa     False     E    TRAPPIST-1e  44.0  False        126.0   

      FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0           0.0           0.0     0.0     0.0        False  
1           9.0          25.0   549.0    44.0         True  
2        3576.0           0.0  6715.0    49.0        False  
3        1283.0         371.0  3329.0   193.0        False  
4          70.0         151.0   565.0     2.0         True  
...         ...           ...     ...     ...          ...  
6601     6819.0           0.0  1643.0    74.0        False  
6602        0.0           0.0     0.0     0.0        False  
6603        0.0        1872.0     1.0     0.0         True  
6604     1049.0           0.0   353.0  3235.0        False  
6605     4688.0           0.0     0.0    12.0         True  

[6606 rows x 12 columns]

- For non-numerical columns, do dummies.

In [143]:
cat_cols = ['HomePlanet', 'Cabin', 'Destination', 'VIP', 'CryoSleep']
df_dummies = pd.get_dummies(df, columns=cat_cols, drop_first=True)

Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Transported  \
0     39.0          0.0        0.0           0.0     0.0     0.0        False   
1     24.0        109.0        9.0          25.0   549.0    44.0         True   
2     58.0         43.0     3576.0           0.0  6715.0    49.0        False   
3     33.0          0.0     1283.0         371.0  3329.0   193.0        False   
4     16.0        303.0       70.0         151.0   565.0     2.0         True   
...    ...          ...        ...           ...     ...     ...          ...   
6601  41.0          0.0     6819.0           0.0  1643.0    74.0        False   
6602  18.0          0.0        0.0           0.0     0.0     0.0        False   
6603  26.0          0.0        0.0        1872.0     1.0     0.0         True   
6604  32.0          0.0     1049.0           0.0   353.0  3235.0        False   
6605  44.0        126.0     4688.0           0.0     0.0    12.0         True   

      HomePlanet_Europa  HomePlanet_Mars  Cabin_B  Cabin_C  Cabin_D  Cabin_E  \
0                  True            False     True    False    False    False   
1                 False            False    False    False    False    False   
2                  True            False    False    False    False    False   
3                  True            False    False    False    False    False   
4                 False            False    False    False    False    False   
...                 ...              ...      ...      ...      ...      ...   
6601               True            False    False    False    False    False   
6602              False            False    False    False    False    False   
6603              False            False    False    False    False    False   
6604               True            False    False    False    False     True   
6605               True            False    False    False    False     True   

      Cabin_F  Cabin_G  Cabin_T  Destination_PSO J318.5-22  \
0       False    False    False                      False   
1        True    False    False                      False   
2       False    False    False                      False   
3       False    False    False                      False   
4        True    False    False                      False   
...       ...      ...      ...                        ...   
6601    False    False    False                      False   
6602    False     True    False                       True   
6603    False     True    False                      False   
6604    False    False    False                      False   
6605    False    False    False                      False   

      Destination_TRAPPIST-1e  VIP_True  CryoSleep_True  
0                        True     False           False  
1                        True     False           False  
2                        True      True           False  
3                        True     False           False  
4                        True     False           False  
...                       ...       ...             ...  
6601                    False      True           False  
6602                    False     False            True  
6603                     True     False           False  
6604                    False     False           False  
6605                     True     False           False  

[6606 rows x 20 columns]

**Perform Train Test Split**

In [163]:
features = df_dummies.drop(columns='Transported')
target = df_dummies['Transported']

In [165]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.20, random_state=42)

In [167]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)


0.7700453857791225

In [169]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [157]:
pred = knn.predict(X_test)

array([ True,  True,  True, ...,  True,  True,  True])

In [159]:
y_test.values

array([ True,  True,  True, ...,  True,  True,  True])

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [11]:
#your code here

- Evaluate your model's performance. Comment it

In [161]:
knn.score(X_test, y_test)

0.7700453857791225

In [175]:
from sklearn.preprocessing import StandardScaler

numerical_features = ["Age", "RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck"]

scaler = StandardScaler()
df[numerical_features] = scaler.fit_transform(df[numerical_features])

In [251]:
df

Age  RoomService  FoodCourt  ShoppingMall       Spa    VRDeck  \
0     0.695413    -0.345756  -0.285355     -0.309494 -0.273759 -0.269534   
1    -0.336769    -0.176748  -0.279993     -0.266112  0.206165 -0.230494   
2     2.002842    -0.279083   1.845163     -0.309494  5.596357 -0.226058   
3     0.282540    -0.345756   0.479034      0.334285  2.636384 -0.098291   
4    -0.887266     0.124056  -0.243650     -0.047470  0.220152 -0.267759   
...        ...          ...        ...           ...       ...       ...   
6601  0.833037    -0.345756   3.777285     -0.309494  1.162518 -0.203876   
6602 -0.749641    -0.345756  -0.285355     -0.309494 -0.273759 -0.269534   
6603 -0.199145    -0.345756  -0.285355      2.938900 -0.272885 -0.269534   
6604  0.213728    -0.345756   0.339621     -0.309494  0.034826  2.600774   
6605  1.039473    -0.150389   2.507673     -0.309494 -0.273759 -0.258887   

      Transported  HomePlanet_Europa  HomePlanet_Mars  Cabin_B  Cabin_C  \
0           False               True            False     True    False   
1            True              False            False    False    False   
2           False               True            False    False    False   
3           False               True            False    False    False   
4            True              False            False    False    False   
...           ...                ...              ...      ...      ...   
6601        False               True            False    False    False   
6602        False              False            False    False    False   
6603         True              False            False    False    False   
6604        False               True            False    False    False   
6605         True               True            False    False    False   

      Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_T  Destination_PSO J318.5-22  \
0       False    False    False    False    False                      False   
1       False    False     True    False    False                      False   
2       False    False    False    False    False                      False   
3       False    False    False    False    False                      False   
4       False    False     True    False    False                      False   
...       ...      ...      ...      ...      ...                        ...   
6601    False    False    False    False    False                      False   
6602    False    False    False     True    False                       True   
6603    False    False    False     True    False                      False   
6604    False     True    False    False    False                      False   
6605    False     True    False    False    False                      False   

      Destination_TRAPPIST-1e  VIP_True  CryoSleep_True  
0                        True     False           False  
1                        True     False           False  
2                        True      True           False  
3                        True     False           False  
4                        True     False           False  
...                       ...       ...             ...  
6601                    False      True           False  
6602                    False     False            True  
6603                     True     False           False  
6604                    False     False           False  
6605                     True     False           False  

[6606 rows x 20 columns]

In [187]:
cat_cols = ['HomePlanet', 'Cabin', 'Destination', 'VIP', 'CryoSleep']
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [271]:
target = df['Transported'].astype(int)
features = df.drop(columns='Transported')    

In [273]:
features.dtypes

Age                          float64
RoomService                  float64
FoodCourt                    float64
ShoppingMall                 float64
Spa                          float64
VRDeck                       float64
HomePlanet_Europa               bool
HomePlanet_Mars                 bool
Cabin_B                         bool
Cabin_C                         bool
Cabin_D                         bool
Cabin_E                         bool
Cabin_F                         bool
Cabin_G                         bool
Cabin_T                         bool
Destination_PSO J318.5-22       bool
Destination_TRAPPIST-1e         bool
VIP_True                        bool
CryoSleep_True                  bool
dtype: object

In [275]:
X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.2, random_state=42)

In [277]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [279]:
log_reg.fit(X_train, y_train)

LogisticRegression()

In [281]:
pred = log_reg.predict(X_test)

In [283]:
pred

array([1, 1, 1, ..., 1, 1, 0])

In [285]:
y_test.values

array([1, 1, 1, ..., 1, 1, 1])

In [287]:
log_reg.score(X_test, y_test)

0.7904689863842662